// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductServices.Data;

namespace ProductServices.Migrations
{
    [DbContext(typeof(ProductServiceContext))]
    [Migration("20200710124103_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductServices.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Img_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img_Url = "https://preview.redd.it/9d69elb5ext41.png?width=1024&auto=webp&s=6c0a8defaaed5d5707e889b10cc1f5e527706b46",
                            Name = "Purple mechanical keyboard",
                            Price = 149.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            Img_Url = "https://preview.redd.it/cw9ax8o8fws41.png?width=1024&auto=webp&s=c78e19c619bfc72933084710a656f39b2f347eea",
                            Name = "Galaxy mechanical keyboard",
                            Price = 249.99000000000001
                        },
                        new
                        {
                            Id = 3,
                            Img_Url = "https://preview.redd.it/z5p7t8t2fst41.png?width=1024&auto=webp&s=14090fd249c2bf94fd2a2d5e3c0701f13f635fe6",
                            Name = "Small grey and beige keyboard",
                            Price = 200.0
                        });
                });

            modelBuilder.Entity("ProductServices.Models.ProductInformation", b =>
                {
                    b.Property<int>("Keyboard_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Switches")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Keyboard_Id");

                    b.ToTable("ProductInformation");

                    b.HasData(
                        new
                        {
                            Keyboard_Id = 1,
                            Language = "US",
                            Layout = "ANSI",
                            Size = 60,
                            Switches = "MX Blues"
                        },
                        new
                        {
                            Keyboard_Id = 2,
                            Language = "US",
                            Layout = "ANSI",
                            Size = 60,
                            Switches = "Gateron Black"
                        },
                        new
                        {
                            Keyboard_Id = 3,
                            Language = "US",
                            Layout = "ANSI",
                            Size = 40,
                            Switches = "Holy Pandas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
